services:
  - type: web
    name: flask-backend
    env: python
    rootDir: back-end  # Specify that the backend is inside the backend folder
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8000
      - key: FLASK_ENV
        value: production
